development:
  host: 'maude.gomoshi.com'
  user: 'enelson'
  pass: 'enelson'
  vhost: 'mobd'

test:
  host: 'maude.gomoshi.com'
  user: 'enelson'
  pass: 'enelson'
  vhost: 'mobd'

staging:
  host: 'smokey.gomoshi.com'
  user: 'mobd'
  pass: 'il_i3Yai'
  vhost: '/jasper_gateway'

production:
  host: 'smokey.gomoshi.com'
  user: 'mobd'
  pass: 'il_i3Yai'
  vhost: '/jasper_gateway'
